services:
  app:
    container_name: configuration-service
    image: configuration-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      SERVER_PORT: ${CONTAINER_PORT}
      GIT_URI: ${GIT_URI}
    networks:
      polar-nw:
        aliases:
          - 'configuration-service'

networks:
  polar-nw:
    name: polar-nw
    external: true